# GitHub Actions workflow with Codeium
name: AI-Enhanced Pipeline
on: [push, pull_request]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install Codeium Enterprise CLI
      - name: Install Codeium CLI
        run: |
          wget https://download.codeium.com/enterprise-cli/latest/codeium_enterprise_cli_linux_amd64.tar.gz
          tar -xzf codeium_enterprise_cli_linux_amd64.tar.gz
          sudo mv codeium_enterprise_cli /usr/local/bin/codeium
          chmod +x /usr/local/bin/codeium
          
      # Verify installation
      - name: Verify Codeium Installation
        run: codeium --version
          
      # Authenticate with Codeium
      - name: Authenticate Codeium
        env:
          CODEIUM_API_KEY: ${{ secrets.CODEIUM_API_KEY }}
        run: |
          codeium auth --api-key "$CODEIUM_API_KEY"
          
      # Run code analysis
      - name: Analyze Code
        run: |
          codeium analyze ./src
          
      # Generate tests
      - name: Generate Tests
        run: |
          codeium generate-tests ./src
