# GitHub Actions workflow with Codeium
name: AI-Enhanced Pipeline
on: [push, pull_request]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install Codeium CLI
      - name: Install Codeium
        run: |
          # Create a temporary directory for download
          mkdir -p /tmp/codeium
          cd /tmp/codeium
          
          # Download the latest release
          curl -L -o codeium.zip https://github.com/Exafunction/codeium/releases/latest/download/codeium-cli-linux-amd64.zip
          
          # Unzip the package
          unzip codeium.zip
          
          # Make it executable and move to a PATH location
          chmod +x codeium-cli
          sudo mv codeium-cli /usr/local/bin/codeium
          
          # Clean up
          cd -
          rm -rf /tmp/codeium
          
      # Authenticate with Codeium
      - name: Authenticate Codeium
        env:
          CODEIUM_API_KEY: ${{ secrets.CODEIUM_API_KEY }}
        run: |
          codeium auth --api-key "$CODEIUM_API_KEY"
          
      # Run code analysis
      - name: Analyze Code
        run: |
          codeium analyze ./src
          
      # Generate tests
      - name: Generate Tests
        run: |
          codeium generate-tests ./src
